servicedesk.frontend/Areas/Admin/Controllers/ServiceItemsController.cs
using IdentityModel.Client;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using servicedesk.frontend.Domain;
using servicedesk.frontend.Domain.Entities;
using servicedesk.frontend.Service;
using System;
using System.IO;
using System.Net.Http;
using System.Net.Http.Json;
using System.Threading.Tasks;

namespace servicedesk.frontend.Areas.Admin.Controllers
{
    [Area("Admin"), Authorize(Roles = "admin")]
    public class ServiceItemsController : Controller
    {
        private readonly DataManager dataManager;
        private readonly IWebHostEnvironment hostingEnvironment;

        public ServiceItemsController(DataManager dataManager, IWebHostEnvironment hostingEnvironment)
        {
            this.dataManager = dataManager;
            this.hostingEnvironment = hostingEnvironment;
        }

        public async Task<ActionResult<string>> EditService(ServiceItem model)
        {
            try
            {
                var apiUrl = new Uri($"https://localhost:44328/api/1.0/Service");
                using (var apiClient = new HttpClient())
                {
                    var accessToken = await HttpContext.GetTokenAsync("access_token");
                    apiClient.SetBearerToken(accessToken);
                    HttpResponseMessage response;
                    if (Guid.Empty == model.Id)
                    {
                        response = await apiClient.PostAsJsonAsync(apiUrl, new { name = model.Title, subtitle = model.Subtitle });
                    }
                    else
                    {
                        response = await apiClient.PutAsJsonAsync(apiUrl, new { id = model.Id, name = model.Title, subtitle = model.Subtitle });
                    }                   
                    response.EnsureSuccessStatusCode();

                    return response.Headers.Location.ToString();
                }
            }
            catch (Exception ex)
            {
                return RedirectToAction("Error", "Home", new { code = ex.ToString() });
            }
        }
        public IActionResult Edit(Guid id)
        {
            var entity = id == default ? new ServiceItem() : dataManager.ServiceItems.GetServiceItemById(id);
            return View(entity);
        }
        [HttpPost]
        public IActionResult Edit(ServiceItem model, IFormFile titleImageFile)
        {
            if (ModelState.IsValid)
            {
                if (titleImageFile != null)
                {
                    model.TitleImagePath = titleImageFile.FileName;
                    using (var stream = new FileStream(Path.Combine(hostingEnvironment.WebRootPath, "images/", titleImageFile.FileName), FileMode.Create))
                    {
                        titleImageFile.CopyTo(stream);
                    }
                }                
                dataManager.ServiceItems.SaveServiceItem(model);
                return RedirectToAction(nameof(HomeController.Index), nameof(HomeController).CutController());
            }
            return View(model);
        }
        [HttpPost]
        public IActionResult Delete(Guid id)
        {
            dataManager.ServiceItems.DeleteServiceItem(id);
            return RedirectToAction(nameof(HomeController.Index), nameof(HomeController).CutController());
        }
    }
}

servicedesk.frontend/Areas/Admin/Views/ServiceItems/Edit.cshtml
@model ServiceItem
@{
    string strTitle = "Редактировать запись";
    ViewBag.Title = strTitle;
}

<script src="~/js/ckeditor/ckeditor.js"></script>

<div>
    <h2>@strTitle</h2>
    <div>
        <form asp-area="Admin" asp-controller="ServiceItems" asp-action="Edit" method="post" enctype="multipart/form-data">
            <input type="hidden" asp-for="Id" />
            <input type="hidden" asp-for="DateAdded" />
            <input type="hidden" asp-for="TitleImagePath" />

            @*<div asp-validation-summary="All"></div>*@
            <div class="div-box">
                <label asp-for="Title"></label>
                <input asp-for="Title" />
                <span asp-validation-for="Title"></span>
            </div>
            <div class="div-box">
                <label asp-for="Subtitle"></label>
                <input asp-for="Subtitle" />
                <span asp-validation-for="Subtitle"></span>
            </div>
            <div class="div-box">
                <label asp-for="Text"></label>
                <textarea asp-for="Text"></textarea>
                <span asp-validation-for="Text"></span>
            </div>
            <div class="div-box">
                <label asp-for="TitleImagePath"></label>
                <input type="file" name="titleImageFile" id="titleImageFile" />
                <div>
                    <img class="img-block" src="~/images/@Model.TitleImagePath" />
                </div>
            </div>
            @*@<div class="div-box">
            <label asp-for="MetaTitle"></label>
            <input asp-for="MetaTitle" />
            <span asp-validation-for="MetaTitle"></span>
        </div>
        <div class="div-box">
            <label asp-for="MetaDescription"></label>
            <input asp-for="MetaDescription" />
            <span asp-validation-for="MetaDescription"></span>
        </div>
        <div class="div-box">
            <label asp-for="MetaKeywords"></label>
            <input asp-for="MetaKeywords" />
            <span asp-validation-for="MetaKeywords"></span>
        </div>*@
            <div class="form__inner">
                <input class="button__add" type="submit" value="Сохранить" />
            </div>

        </form>
    </div>
</div>



<script>
    window.onload = function () {
        var newCKEdit = CKEDITOR.replace('@Html.IdFor(x=>x.Text)');
        newCKEdit.updateElement();
    }
</script>