servicedesk.frontend/Areas/Admin/Controllers/TextFieldsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using servicedesk.frontend.Domain;
using servicedesk.frontend.Domain.Entities;
using servicedesk.frontend.Service;

namespace servicedesk.frontend.Areas.Admin.Controllers
{
    [Area("Admin"), Authorize(Roles = "admin")]
    public class TextFieldsController : Controller
    {
        private readonly DataManager dataManager;

        public TextFieldsController(DataManager dataManager)
        {
            this.dataManager = dataManager;
        }

        public IActionResult Edit(string codeWord)
        {
            var entity = dataManager.TextFields.GetTextFieldByCodeWord(codeWord);
            return View(entity);
        }

        [HttpPost]
        public IActionResult Edit(TextField model)
        {
            if (ModelState.IsValid)
            {
                dataManager.TextFields.SaveTextField(model);
                return RedirectToAction(nameof(HomeController.Index), nameof(HomeController).CutController());
            }
            return View(model);
        }
    }
}

servicedesk.frontend/Areas/Admin/Views/TextFields/Edit.cshtml
@model TextField
@{
    string strTitle = "Редактировать запись";
    ViewBag.Title = strTitle;
}

<script src="~/js/ckeditor/ckeditor.js"></script>

<div>
    <h2>@strTitle</h2>
    <div>
        <form asp-area="Admin" asp-controller="TextFields" asp-action="Edit" method="post" enctype="multipart/form-data">
            <input type="hidden" asp-for="Id" />
            <input type="hidden" asp-for="DateAdded" />
            <input type="hidden" asp-for="CodeWord" />

            @*<div asp-validation-summary="All"></div>*@
            <div class="div-box">
                <label asp-for="Title"></label>
                <input asp-for="Title" />
                <span asp-validation-for="Title"></span>
            </div>
            <div class="div-box">
            </div>
            <div class="div-box">
                <label asp-for="Text"></label>
                <textarea asp-for="Text"></textarea>
                <span asp-validation-for="Text"></span>
            </div>
            @*<div class="div-box">
                    <label asp-for="MetaTitle"></label>
                    <input asp-for="MetaTitle" />
                    <span asp-validation-for="Text"></span>
                </div>
                <div class="div-box">
                    <label asp-for="MetaDescription"></label>
                    <input asp-for="MetaDescription" />
                    <span asp-validation-for="MetaDescription"></span>
                </div>
                <div class="div-box">
                    <label asp-for="MetaKeywords"></label>
                    <input asp-for="MetaKeywords" />
                    <span asp-validation-for="MetaKeywords"></span>
                </div>*@
            <div class="form__inner">
                <input class="button__add" type="submit" value="Сохранить" />
            </div>

        </form>
    </div>
</div>



<script>
    window.onload = function () {
        var newCKEdit = CKEDITOR.replace('@Html.IdFor(x=>x.Text)');
        newCKEdit.updateElement();
    }
</script>